language: node_js
node_js:
  - lts/*
  - node

cache:
  directories:
    - .cache/
    - .next/cache/

script:
  - yarn type-check
  - yarn lint
  - yarn build

deploy:
  - provider: npm
    edge: true
    run_script: publish
    on:
      tags: true
      node_js: lts/*
