language: node_js
node_js:
  - lts/*
  - node

cache:
  directories:
    - packages/example-gatsby/.cache/
    - packages/example-nextjs/.next/cache/

script:
  - yarn lint
  - yarn build
  - yarn type-check
  - echo glaze.js.org > ./packages/website/build/CNAME

deploy:
  - provider: pages:git
    edge: true
    local_dir: ./packages/website/build/
    on:
      branch: master
  - provider: npm
    edge: true
    run_script: publish
    on:
      tags: true
      node_js: lts/*
