language: node_js
node_js:
  - lts/*
  - node

jobs:
  include:
    - yarn type-check
    - yarn lint
    - yarn build

    - stage: deploy
      if: tag IS present
      node_js: lts/*
      deploy:
        provider: npm
        edge: true
        run_script: publish
